- name: Update vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Install Plug
  block:
    - file:
        path: "{{ ansible_env.HOME }}/.vim/autoload"
        state: directory
    - get_url: 
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"

- name: Install vim plugins
  command: vim +PlugInstall +qall
